config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  root 'groups#index'
  
  get 'favorites' => 'posts#favorites'
  get 'trending' => 'posts#trending'
  get 'search' => 'users#search', as: :users_search

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :groups do 
    resources :posts do
      member do
        put "like" => "posts#upvote"
        put "clap" => "posts#claps"
        delete "clap" => "posts#unclap"
      end
      resources :comments do
        member do
          put "clap" => "comments#claps"
          delete "clap" => "comments#unclap"
        end
      end
    end
    resources :users, only: [:index]
  end

  resources :users
  
  # API Routes

  namespace 'api' do
    namespace 'v1' do
      # devise_for :users
      resources :groups
      # , :only=>[:index, :show]
      resources :users
      resources :posts
      resources :comments
      resources :user_comment_claps
      resources :user_post_claps
      resources :user_post_bookmarks
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  group_id   :integer
#  title      :string
#  text       :string
#  category   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_posts_on_group_id  (group_id)
#  index_posts_on_user_id   (user_id)
#

class Post < ApplicationRecord
  
  enum category: [ 'Idea', 'Pregunta', 'Anuncio' ]

  belongs_to :user
  belongs_to :group

  has_many :comments
  has_many :user_post_claps
  has_many :user_post_bookmarks

  acts_as_votable
  
end

app/controllers/api/v1/posts_controller.rb
module  Api
  module V1
    class PostsController < ApplicationController
      skip_before_action :verify_authenticity_token
      def index
        posts = Post.order('created_at DESC')
        render json: {status: 'SUCCESS', message:'Loaded posts', data:posts},status: :ok
      end

      def show
        posts = Post.find(params[:id])
        render json: {status: 'SUCCESS', message:'Loaded post', data:posts},status: :ok
      end

      def create
        post = Post.new(post_params)
        # @post.post = current_post

        if post.save
          render json: {status: 'SUCCESS', message:'Saved post', data:post},status: :ok
        else
          render json: {status: 'ERROR', message:'post not saved', data:post.errors},status: :unprocessable_entity
        end
      end

      def destroy
        post = Post.find(params[:id])
        post.destroy
        render json: {status: 'SUCCESS', message:'Deleted post', data:post},status: :ok
      end

      def update
        post = Post.find(params[:id])
        if post.update_attributes(post_params)
          render json: {status: 'SUCCESS', message:'Updated post', data:post},status: :ok
        else
          render json: {status: 'ERROR', message:'post not updated', data:post.errors},status: :unprocessable_entity
        end
      end

      private

      def post_params
        params.permit(:user_id, :group_id, :title, :text, :category)
      end


    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :claps]
    before_action :set_group, only: [:index, :create]
    
    # GET /posts
    # GET /posts.json
    def index
        @user = current_user
        @groups = current_user.groups
        @group =  Group.find(params[:group_id])
        @posts = @group.posts.reverse
        @claps = UserPostClap.all
    end
    
    def search
        @posts = Post.search_by_user(params[:keywords], current_user)
    end
    
    def claps
        @clap = UserPostClap.create(user_id: current_user.id, post: @post )
        # @post = Post.new(post_params.merge!({user_id: current_user.id, group: @group}))
        # @post.user = current_user
        # @claps = UserPostClap.find_by(post_id: @post)
        if params[:favorites]
            redirect_to favorites_path
            return
            
        elsif params[:trending]
            redirect_to trending_path
            return
        elsif params[:show]
            redirect_to group_post_path
            return
        else
            redirect_to group_posts_path
        end
    end

    def unclap
        @user = current_user
        @groups = current_user.groups
        @group =  Group.find(params[:group_id])
        @posts = @group.posts
        @claps = UserPostClap.find(params[:id])
        # find all claps with this user id
        # last_clap = current_user.user_post_claps
        # puts last_clap
        puts "hereeeeeeee"
        # @clap = UserPostClap.where(id: [last_clap]).pluck(:id)
        puts @claps
        @claps.destroy
        if params[:favorites]
            redirect_to favorites_path
            return
            
        elsif params[:trending]
            redirect_to trending_path
            return
        elsif params[:show]
            redirect_to group_post_path
            return
        else
            redirect_to group_posts_path
        end
    end

     def upvote 
        # @post.upvote_from current_user
        @vote = ActsAsVotable::Vote.find_by(votable_type: "Post", votable_id: @post.id, voter_id: current_user.id)
        if !@vote
            current_user.likes @post
        else
            if(@vote.vote_flag)
                @vote.destroy
            else
                @vote.update(vote_flag: true)
            end
        end
        if params[:favorites]
            redirect_to favorites_path
        elsif params[:trending]
            redirect_to trending_path
        elsif params[:show]
            redirect_to group_post_path
        else
            redirect_to group_posts_path
        end
       
    end 

    def downvote
        @post.downvote_from current_user
        redirect_to group_posts_path

    end

    def trending
        @group =  Group.find_by(params[:id])
        @groups = current_user.groups
        # @trending = posts.all.sort_by{|post| post.user_post_claps.size}.reverse
        @posts = Post.all
        @claps = UserPostClap.all
    end

    def favorites
        @group =  Group.find_by(params[:id])
        @posts = Post.all
        @groups = current_user.groups
        @favorites = current_user.votes.up
        @claps = UserPostClap.all
    end
    # GET /posts/1
    # GET /posts/1.json
    def show
        @groups = current_user.groups
        @group =  Group.find(params[:group_id])
        @posts = @group.posts 
        @post = @posts.find_by(id: params[:id])   
        @comments = @post.comments
        @comment = Comment.new
        @claps = UserPostClap.all
        @claps_comment = UserCommentClap.all
   
    end
    
    # GET /posts/new
    def new
        @groups = current_user.groups
        @group =  Group.find(params[:group_id])
        @posts = @group.posts
        @post = Post.new
    end
    
    # GET /posts/1/edit
    def edit
        @groups = current_user.groups
        @group =  Group.find(params[:group_id])
        @posts = @group.posts 
        @post = @posts.find_by(id: params[:id])
    end
    
    # POST /posts
    # POST /posts.json
    def create
        @groups = current_user.groups
        @group =  Group.find(params[:group_id])
        @posts = @group.posts
        # @post = @group.posts.build(post_params)
        @post = Post.new(post_params.merge!({user_id: current_user.id, group: @group}))
        # @post.user = current_user
    
        respond_to do |format|
        if @post.save
            format.html { redirect_to group_posts_path, notice: 'El post fue creado exitosamente' }
            format.json { render :show, status: :created, location: @post }
        else
            format.html { render :index }
            format.json { render json: @post.errors, status: :unprocessable_entity }
        end
        end
    end
    
    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
        respond_to do |format|
        if @post.update(post_params)
            format.html { redirect_to group_posts_path(params[:group_id]), notice: 'El empleado fue actualizado exitosamente.' }
            format.json { render :show, status: :ok, location: @post }
        else
            format.html { render :edit }
            format.json { render json: @post.errors, status: :unprocessable_entity }
        end
        end
    end
    
    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
        @post.destroy
        respond_to do |format|
        format.html { redirect_to group_posts_path, notice: 'El empleado fue eliminado exitosamente.' }
        format.json { head :no_content }
        end
    end
    
    private
        # Use callbacks to share common setup or constraints between actions.
        def set_post
            @post = Post.find_by(id: params[:id])
            # @posts = @group.posts
        end
    
        def set_group
            @group = Group.find_by(id: params[:group_id])
        end
    
        # Never trust parameters from the scary internet, only allow the white list through.
        def post_params
            params.require(:post).permit(:title, :text, :category, :user_id)
        end
    end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form_post.html.haml
.col-8
    .container.borderg.mt-1.ml-1.br2
        = form_for [@group, @post] do |f|
            .row
                .col-1.p0
                    = link_to '← Back', group_posts_path, class: 'btn btn-light'
                .col-1.text-center.mt-5.mb-2.mr-1.ml-1
                    = image_tag current_user.avatar.url(:medium), class: "rounded-circle round-image-small" 

                .col-9.mt-5.mb-3.titlepost
                    .form-group
                        %b
                        = f.label 'Titulo:'
                        = f.text_field :title, class: 'form-control', required: true
                
            .row
                .col-11.mb-3.ml-4
                    .form-group
                        %b
                        -# = f.label 'Texto'
                        = f.hidden_field :text, class: 'form-control', id: :post_body
                        %trix-editor{:input => "post_body", required: true}
                        
            .row.footerpostform.formwidth.br2.fwhite
                .col-5.fechapost
                    .form-group{:action => ""}
                        %label.ml-5.mt-2.mr-2#labanuncio                                    
                            = f.radio_button :category, "Anuncio", class: 'form-control', required: true
                            %i.fas.fa-bullhorn.imgbox 
                        %label.ml-5.mt-2.mr-2#labpregunta 
                            = f.radio_button :category , "Pregunta" , class: 'form-control', required: true
                            %i.fas.fa-question.imgbox
                        %label.ml-5.mt-2.ml-2#labidea       
                            = f.radio_button :category, "Idea", class: 'form-control', required: true 
                            %i.fas.fa-lightbulb.imgbox
                         
                    %label.categoriapost
                        %p#ingresacategoria
                            Para publicar selecciona una categoria
                        %p#anunciocat.ml-5
                            Tu post es un Anuncio
                        %p#ideacat.ml-5    
                            Tu post es una Idea
                        %p#preguntacat.ml-5
                            Tu post es una Pregunta                     
                .col-3        
                .col-2.mt-4.text-right
                    = f.submit 'Publicar', class: 'btn btn-light viaje borderg'
                 

            

app/views/posts/_post.html.haml
.col-8
    - @posts.each do |post|
        .container.mt-3.ml-1.br2.borderg.p0.mb-5#containerpost
            .col-12.p0
                .col-1.text-center.mt-2.mb-2.float-left.front.d-inline-block.p0
                    = link_to "/search?utf8=✓&keywords=#{post.user.name}&button=" do
                    
                        = image_tag post.user.avatar.url(:medium), class: "rounded-circle round-image-small borderg postimg" 
                .col-10.titlepost.titlepostmargin
                    = link_to group_post_path(@group.id, post.id) do
                        
                        = post.title 
                    
                    .row.fxs.ml-1.fsmall
                        
                        - if post.category == "Anuncio"
                            %i.fas.fa-bullhorn.mr-1
                        - elsif post.category == "Pregunta"
                            %i.fas.fa-question.mr-1
                        - else
                            %i.fas.fa-lightbulb.mr-1
                        = post.category        
                        por
                        %a.fsmall.ml-1.namecolor{:href => "/search?utf8=✓&keywords=#{post.user.name}&button="}
                            = post.user.name 
                    
                    
            .row
                .col-11.mb-3
                    = truncate( (sanitize post.text), :length => 300)
            .row.footerpost.br2.fwhite
                .col-4.fechapost.mt-1
                    = time_ago_in_words(post.created_at)
                .col-3
                .col-2
                    -# = link_to api_v1_user_post_clap_path(@group.id, post.id), method: :delete do     
                    -#     %i.fas.fa-ban
                    = link_to clap_group_post_path(@group.id, post.id), method: :put do     
                        %i.far.fa-hand-peace
                            = @claps.where(post_id: post.id).size
                .col-2 
                    = link_to group_post_path(@group.id, post.id) do
                        %i.fas.fa-comments
                        = post.comments.size    
                .col-1
                    = link_to like_group_post_path(@group.id, post.id), method: :put do 
                        - if ActsAsVotable::Vote.find_by(votable_id: post.id,voter_id: @user.id) != nil
                        
                            %i.fas.fa-star{style: "color: orange"}
                          
                        - else 
                            %i.fas.fa-star{style: "color: white"}
                    

                                

app/views/posts/_user_post.html.haml
.modal.fade{id: "#{@posts.user.name}", "aria-hidden" => "true", "aria-labelledby" => "exampleModalCenterTitle", :role => "dialog", :tabindex => "-1"}
    .modal-dialog.modal-dialog-centered{:role => "document"}
        .modal-content
            .modal-header.commentnew
                Perfil                                                                                
                %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                %span{"aria-hidden" => "true"}
                    %i.fas.fa-times
            .modal-body
                %div#exampleModalLongTitle.text-center.modal-title.namexp
                    = post.user.name
                %div#exampleModalLongTitle.text-center.modal-title.namexp
                    = image_tag post.user.avatar.url(:medium), class: "rounded-circle round-image-50" 
                %hr.lower
                %div#exampleModalLongTitle.text-center
                    = post.user.title
                %hr.lower
                %div#exampleModalLongTitle.text-center
                    = post.user.email
                %hr.lower
                %div#exampleModalLongTitle.text-center
                    = post.user.mobile   

app/views/posts/edit.html.haml
= render partial: 'posts/form_post', locals: { form_args: @employee }
    

app/views/posts/favorites.html.haml
.col-8
    - @posts.each do |post|
        - if current_user.voted_for? post 
            .container.mt-3.ml-1.br2.borderg.p0.mb-5#containerpost
                .col-12.p0
                    .col-1.text-center.mt-2.mb-2.float-left.front.d-inline-block.p0
                        = link_to "/search?utf8=✓&keywords=#{post.user.name}&button=" do
                        
                            = image_tag post.user.avatar.url(:medium), class: "rounded-circle round-image-small borderg postimg" 
                    .col-10.titlepost.titlepostmargin
                        = link_to group_post_path(@group.id, post.id) do
                            
                            = post.title 
                        
                        .row.fxs.ml-1.fsmall
                            
                            - if post.category == "Anuncio"
                                %i.fas.fa-bullhorn.mr-1
                            - elsif post.category == "Pregunta"
                                %i.fas.fa-question.mr-1
                            - else
                                %i.fas.fa-lightbulb.mr-1
                            = post.category        
                            por
                            %a.fsmall.ml-1.namecolor{:href => "/search?utf8=✓&keywords=#{post.user.name}&button="}
                                = post.user.name 
                        
                        
                .row
                    .col-11.mb-3
                        = truncate( (sanitize post.text), :length => 300)
                .row.footerpost.br2.fwhite
                    .col-4.fechapost.mt-1
                        = time_ago_in_words(post.created_at)
                    .col-3
                    .col-2
                        = link_to clap_group_post_path(@group.id, post.id), method: :put do     
                            %i.far.fa-hand-peace
                                = @claps.where(post_id: post.id).size
                    .col-2 
                        = link_to group_post_path(@group.id, post.id) do
                            %i.fas.fa-comments
                            = post.comments.size    
                    .col-1
                        = link_to like_group_post_path(@group.id, post.id, favorites: true), method: :put do 
                            - if ActsAsVotable::Vote.find_by(votable_id: post.id) == nil
                                %i.fas.fa-star{style: "color: white"}
                          
                            - else 
                                %i.fas.fa-star{style: "color: orange"}
                       

app/views/posts/index.html.haml
= render 'posts/post'

app/views/posts/new.html.haml
= render 'form_post'

app/views/posts/show.html.haml
.col-8
    .container.borderg.mt-1.ml-1.br2
        .row
            .col-1.p0
                = link_to '← Back', group_posts_path, class: 'btn btn-light'
            .col-1.text-center.mt-2.mb-2
                = link_to "/search?utf8=✓&keywords=#{@post.user.name}&button=" do
                    = image_tag @post.user.avatar.url(:medium), class: "rounded-circle round-image-small borderg " 
            .col-8.mt-4.mb-3.titlepost
                = @post.title
                .row.fxs.ml-1
                    - if @post.category == "Anuncio"
                        %i.fas.fa-bullhorn
                    - elsif @post.category == "Pregunta"
                        %i.fas.fa-question
                    - else
                        %i.fas.fa-lightbulb
                    = @post.category
                    por
                    %a.fsmall.ml-1.namecolor{:href => "/search?utf8=✓&keywords=#{@post.user.name}&button="}
                        = @post.user.name
                
            .col-2.text-right.pr-0
                - if current_user.id == @post.user.id
                    = link_to edit_group_post_path(@group.id, @post.id), class: 'btn btn-light' do
                        Edit
                        %i.fas.fa-edit
                            
        .row
            .col-11.mb-3.ml-4
                = @post.text.html_safe
        .row
            .col-4.fechapost.mt-1
                = time_ago_in_words(@post.created_at)
            .col-3
            .col-2
                = link_to clap_group_post_path(@group.id, @post.id, show: true), method: :put do     
                    %i.far.fa-hand-peace
                        = @claps.where(post_id: @post.id).size
            .col-2 
                = link_to group_post_path(@group.id, @post.id) do
                    %i.fas.fa-comments
                    = @post.comments.size    
            .col-1
                = link_to like_group_post_path(@group.id, @post.id, show: true), method: :put do 
                    - if ActsAsVotable::Vote.find_by(votable_id: @post.id) == nil
                        
                        %i.far.fa-star{style: "color: black"}
                        
                    - else 
                        %i.fas.fa-star{style: "color: orange"}
    .col-12
        - @comments.each do |comment|
            .container.ml-1
                .col-12
                    .col-1.d-inline-block.float-left.mt-2.front.mnega
                        = link_to "/search?utf8=✓&keywords=#{comment.user.name}&button=" do
                            = image_tag comment.user.avatar.url(:medium), class: "rounded-circle round-image-small borderg"
                    .col-10.fs.d-inline-block.mt-2.comment
                        %a.fs.namecolor{:href => "/search?utf8=✓&keywords=#{comment.user.name}&button="}
                            = comment.user.name
                            .row       
                                %spam.fxxs.ml-4
                                    = time_ago_in_words(comment.created_at)                                       
                        .row.fxs.mt-2
                            .col-9.ml-3.comment.d-inline-block 
                                = comment.text.html_safe               
                            .col-2.fxs.mb-2.d-inline-block.text-right 
                                = link_to clap_group_post_comment_path(@group.id, @post.id, comment_id: comment.id), method: :put do     
                                    %i.far.fa-hand-peace
                                        = @claps_comment.where(comment_id: comment.id).size
                                        
        = render "comments/form"
   

app/views/posts/trending.html.haml
.col-8
    - @groups.each do |group|
        - group.posts.all.sort_by{|post| post.user_post_claps.size}.reverse.each do |post|          
            .container.mt-3.ml-1.br2.borderg.p0.mb-5#containerpost
                .col-12.p0
                    .col-1.text-center.mt-2.mb-2.float-left.front.d-inline-block.p0
                        = link_to "/search?utf8=✓&keywords=#{post.user.name}&button=" do
                        
                            = image_tag post.user.avatar.url(:medium), class: "rounded-circle round-image-small borderg postimg" 
                    .col-10.titlepost.titlepostmargin
                        = link_to group_post_path(@group.id, post.id) do
                            
                            = post.title 
                        
                        .row.fxs.ml-1.fsmall
                            
                            - if post.category == "Anuncio"
                                %i.fas.fa-bullhorn.mr-1
                            - elsif post.category == "Pregunta"
                                %i.fas.fa-question.mr-1
                            - else
                                %i.fas.fa-lightbulb.mr-1
                            = post.category        
                            por
                            %a.fsmall.ml-1.namecolor{:href => "/search?utf8=✓&keywords=#{post.user.name}&button="}
                                = post.user.name 
                        
                        
                .row
                    .col-11.mb-3
                        = truncate( (sanitize post.text), :length => 300)
                .row.footerpost.br2.fwhite
                    .col-4.fechapost.mt-1
                        = time_ago_in_words(post.created_at)
                    .col-3
                    .col-2
                        = link_to clap_group_post_path(@group.id, post.id, trending: true), method: :put do     
                            %i.far.fa-hand-peace
                                = @claps.where(post_id: post.id).size
                            -# = @claps.size
                        -# - else 
                        -#     = link_to like_group_post_path(@group.id, post.id), method: :put do     
                        -#         %i.far.fa-hand-peace
                        -#         = post.get_likes.size
                    .col-2 
                        = link_to group_post_path(@group.id, post.id) do
                            %i.fas.fa-comments
                            = post.comments.size    
                    .col-1
                        -# - if current_user.voted_for? post 
                            -# = link_to unlike_group_post_path(@group.id, post.id), method: :put do     
                            -#     %i.fas.fa-bookmark{style: "color: blue"}
                        -# - else 
                        
                        


                        = link_to like_group_post_path(@group.id, post.id, trending: true), method: :put do 
                            - if ActsAsVotable::Vote.find_by(votable_id: post.id,voter_id: current_user.id) != nil
                            
                                %i.fas.fa-star{style: "color: orange"}
                            
                            - else 
                                %i.fas.fa-star{style: "color: white"}        