config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  root 'groups#index'
  
  get 'favorites' => 'posts#favorites'
  get 'trending' => 'posts#trending'
  get 'search' => 'users#search', as: :users_search

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :groups do 
    resources :posts do
      member do
        put "like" => "posts#upvote"
        put "clap" => "posts#claps"
        delete "clap" => "posts#unclap"
      end
      resources :comments do
        member do
          put "clap" => "comments#claps"
          delete "clap" => "comments#unclap"
        end
      end
    end
    resources :users, only: [:index]
  end

  resources :users
  
  # API Routes

  namespace 'api' do
    namespace 'v1' do
      # devise_for :users
      resources :groups
      # , :only=>[:index, :show]
      resources :users
      resources :posts
      resources :comments
      resources :user_comment_claps
      resources :user_post_claps
      resources :user_post_bookmarks
    end
  end
end

app/views/layouts/_body.html.haml
.col-8.posts 
    -# = render "posts/post"
    

app/views/layouts/_footer.html.haml
.col-12.footer
    %div.align-top
        .col-8
            %a{target: "_blank" , :href => "https://www.instagram.com/academia_hack/?hl=en"} 
                %i.fab.icon_footer.fa-instagram.float-left
        .col-8
            %a{target: "_blank" , :href => "https://www.facebook.com/AcademiaHack/"}
                %i.fab.icon_footer.fa-facebook-f.float-left
        .col-8
            %a{target: "_blank" , :href => "https://twitter.com/academia_hack?lang=en"}
                %i.fab.icon_footer.fa-twitter.float-left
  

app/views/layouts/_header.html.haml
.col-12.header.align-content-stretch
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
        %a.navbar-brand{:href => groups_path} 
            =image_tag "hackboard_logo.svg", class: "logo"
        %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
            %span.navbar-toggler-icon
        #navbarSupportedContent.collapse.navbar-collapse
            %ul.navbar-nav.fullw           
                %li.nav-item.col-3.icon-top
                    %a.nav-link.headerbut{:href => trending_path} 
                        %i.fas.icon.fa-chart-line.fcblue.d-flex
                            %p.d-none.d-md-inline.fcblue 
                                Tendencia
                %li.nav-item.col-3.icon-top
                    %a.nav-link.headerbut{:href => favorites_path} 
                        %i.fas.icon.fa-star.fcblue.d-flex
                            %p.d-none.d-md-inline.fcblue 
                                Favoritos

                %li.nav-item.col-3.icon-top-bar
    
                    -# %input.form-control.mr-sm-2.ml-4{"aria-label" => "Search", :placeholder => "Buscar...", :type => "search", :style => "width: 420px;"}/
                    = form_tag users_search_path, class: 'd-flex', method: :get do
                        = text_field_tag :keywords, params[:keywords], id: 'searchText', class: 'flex-2 form-control', placeholder: 'Busqueda de usuarios'
                        = button_tag(type: "submit", id: 'searchButton', class: "btn commentnew") do
                            = icon :fas, :search
                %li.nav-item.col-3.icon-topprofile 
                    .nav-item.dropdown(class= "allign-left d-table-row")
                        %a#navbarDropdown.nav-link.dropdown-toggle.profilebut.fcblue{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                            %i.fas.fa-user
                            %spam.d-none.d-md-inline  
                                = current_user.name
                        .dropdown-menu.borderg.p0{"aria-labelledby" => "navbarDropdown"}
                            .modal-header.commentnew
                                Perfil 
                                %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                                %span{"aria-hidden" => "true"}
                                    %i.fas.fa-times
                            .modal-body
                                %div#exampleModalLongTitle.text-center.modal-title.namexp
                                    = current_user.name
                                = image_tag current_user.avatar.url(:medium), class: "rounded-circle round-image-50" 
                                %hr.lower
                                %div#exampleModalLongTitle.text-center
                                    = current_user.title
                                %hr.lower
                                %div#exampleModalLongTitle.text-center
                                    = current_user.email
                                %hr.lower
                                %div#exampleModalLongTitle.text-center
                                    = current_user.mobile   
                                %hr.lower    
                                = link_to 'Editar', edit_user_path(current_user) , class: 'btn btn-light fullw borderg'
                                %hr.lower                                           
                                = link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'btn btn-light fullw logout borderg'

app/views/layouts/_sidebar.html.haml
.col-3
    = link_to  new_group_post_path(@group) do
        %button.btn.btn-light.fullw.shadow{:type => "button"}
            Nuevo Post
            %i.fas.fa-plus-square
    #v-pills-tab.nav.flex-column.nav-pills.backblue.br2.shadow.grouphov{"aria-orientation" => "vertical", :role => "tablist"}
        = render "groups/group_names"
    -# %a#v-pills-home-tab.nav-link.active.text-center.fwhite.grouphov{"aria-controls" => "v-pills-home", "aria-selected" => "true", "data-toggle" => "pill", :href => "#v-pills-home", :role => "tab"}
        
            -# %i.fas.fa-user{:href => "group/users"}
        -# %a#v-pills-profile-tab.nav-link.text-center.fwhite.grouphov{"aria-controls" => "v-pills-profile", "aria-selected" => "false", "data-toggle" => "pill", :href => "#v-pills-profile", :role => "tab"} 
        -#     Promo 8
        -#     %i.fas.fa-user{:href => "group/users"}
            
        -# %a#v-pills-messages-tab.nav-link.text-center.fwhite.grouphov{"aria-controls" => "v-pills-messages", "aria-selected" => "false", "data-toggle" => "pill", :href => "#v-pills-messages", :role => "tab"} Viajelandia internacional
        -# %a#v-pills-settings-tab.nav-link.text-center.fwhite.grouphov{"aria-controls" => "v-pills-settings", "aria-selected" => "false", "data-toggle" => "pill", :href => "#v-pills-settings", :role => "tab"} tech

        = render 'users/user', user: current_user

app/views/layouts/application.html.haml
!!!
%html
  %head
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css",:rel => "stylesheet"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HackBoard
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if user_signed_in?
      = render partial: "layouts/header"
      .row
        = render partial: "layouts/sidebar"
        = yield  
      = render partial: "layouts/footer"
    - else
      .container.mt-5
      = yield
   